name: Build all LaTeX files to PDF

on:
  push:
    paths:
      - '**/*.tex'
      - '!**/output/*'  # Exclude specific directories if needed
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Find and compile all .tex files
        run: |
          find . -name "*.tex" -not -path "./.github/*" | while read texfile; do
            echo "Compiling $texfile..."
            dir=$(dirname "$texfile")
            cd "$dir" || exit
            filename=$(basename "$texfile" .tex)
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode "$filename.tex"
            cd - || exit
          done

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generated PDFs from LaTeX"
          file_pattern: '**/*.pdf'
          branch: ${{ github.ref_name }}